version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ddjdpdhvzbrosh
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: peta_stack_example_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build:
      context: .
    env_file:
      - .env
    environment:
      PORT: 4001
    ports:
      - "4001:4001"
    depends_on:
      - db
volumes:
  pgdata:
